(define (main)
  (setPort (open (getElement ScamArgs 1) 'read))
  (define arg1 (readInt))
  (define res (ramanujanr arg1))
  (println "(ramanujanr " arg1 ") is " (fmt "%.25f" res))
  (println "$4$")
)

(define (ramanujanr depth)
  (define (ramanujanr-inner curr)
    (if (= depth curr)
      (sqrt (+ 6 curr))
      (sqrt (+ (+ curr 6) (* (+ curr 2) (ramanujanr-inner (+ curr 1)))))
    )
  )
  (ramanujanr-inner 0)
)
