(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (readArgs)
)

(define (readArgs)
    (define env this)
    (define (iter expr)
        (if (not (eof?))
            (begin (eval expr env) 
                (iter (readExpr))
            )
        )
    )
    (iter (readExpr))
)

(define (range a b i)
    (if (< a b)
        (cons a (range (+ a i) b i))
        nil
    )
)

(define (for-loop result function)
    (define (iter i len)
        (cond
            ((< i len)
                (function (getElement result i))
                (iter (+ i 1) len)
            )
        )
    )
    (iter 0 (length result))
)