all:
	@make task1
	@make task2
	@make task3
	@make task4
	@make task5
	@make task6
	@make task7
	@make task8
	#echo "All current tasks passed!"

task1:
	#echo "Task1.0:"
	@scam -r task1.scm task1.0 > task1.0.results
	#echo "Results:"
	#cat task1.0.results
	#echo "Expected:"
	#cat task1.0.expected
	@diff -s -q task1.0.results task1.0.expected

	#echo "Task1.1:"
	@scam -r task1.scm task1.1 > task1.1.results
	#echo "Results:"
	#cat task1.1.results
	#echo "Expected:"
	#cat task1.1.expected
	@diff -s -q task1.1.results task1.1.expected

	#echo "Task1.2:"
	@scam -r task1.scm task1.2 > task1.2.results
	#echo "Results:"
	#cat task1.2.results
	#echo "Expected:"
	#cat task1.2.expected
	@diff -s -q task1.2.results task1.2.expected

	#echo "Task1.3:"
	@scam -r task1.scm task1.3 > task1.3.results
	#echo "Results:"
	#cat task1.3.results
	#echo "Expected:"
	#cat task1.3.expected
	@diff -s -q task1.3.results task1.3.expected

	#echo "Task1.4:"
	@scam -r task1.scm task1.4 > task1.4.results
	#echo "Results:"
	#cat task1.4.results
	#echo "Expected:"
	#cat task1.4.expected
	@diff -s -q task1.4.results task1.4.expected

	#echo "Task1.5:"
	@scam -r task1.scm task1.5 > task1.5.results
	#echo "Results:"
	#cat task1.5.results
	#echo "Expected:"
	#cat task1.5.expected
	@diff -s -q task1.5.results task1.5.expected

	#echo "Task1.6:"
	@scam -r task1.scm task1.6 > task1.6.results
	#echo "Results:"
	#cat task1.6.results
	#echo "Expected:"
	#cat task1.6.expected
	@diff -s -q task1.6.results task1.6.expected

	#echo "Task1.7:"
	@scam -r task1.scm task1.7 > task1.7.results
	#echo "Results:"
	#cat task1.7.results
	#echo "Expected:"
	#cat task1.7.expected
	@diff -s -q task1.7.results task1.7.expected

	#echo "Task1.8:"
	@scam -r task1.scm task1.8 > task1.8.results
	#echo "Results:"
	#cat task1.8.results
	#echo "Expected:"
	#cat task1.8.expected
	@diff -s -q task1.8.results task1.8.expected

	#echo "Task1.9:"
	@scam -r task1.scm task1.9 > task1.9.results
	#echo "Results:"
	#cat task1.9.results
	#echo "Expected:"
	#cat task1.9.expected
	@diff -s -q task1.9.results task1.9.expected

task2:
	#echo "Task2.0:"
	@scam -r task2.scm task2.0 > task2.0.results
	#echo "Results:"
	#cat task2.0.results
	#echo "Expected:"
	#cat task2.0.expected
	@diff -s -q task2.0.results task2.0.expected

	#echo "Task2.1:"
	@scam -r task2.scm task2.1 > task2.1.results
	#echo "Results:"
	#cat task2.1.results
	#echo "Expected:"
	#cat task2.1.expected
	@diff -s -q task2.1.results task2.1.expected

	#echo "Task2.2:"
	@scam -r task2.scm task2.2 > task2.2.results
	#echo "Results:"
	#cat task2.2.results
	#echo "Expected:"
	#cat task2.2.expected
	@diff -s -q task2.2.results task2.2.expected

	#echo "Task2.3:"
	@scam -r task2.scm task2.3 > task2.3.results
	#echo "Results:"
	#cat task2.3.results
	#echo "Expected:"
	#cat task2.3.expected
	@diff -s -q task2.3.results task2.3.expected

	#echo "Task2.4:"
	@scam -r task2.scm task2.4 > task2.4.results
	#echo "Results:"
	#cat task2.4.results
	#echo "Expected:"
	#cat task2.4.expected
	@diff -s -q task2.4.results task2.4.expected

	#echo "Task2.5:"
	@scam -r task2.scm task2.5 > task2.5.results
	#echo "Results:"
	#cat task2.5.results
	#echo "Expected:"
	#cat task2.5.expected
	@diff -s -q task2.5.results task2.5.expected

	#echo "Task2.6:"
	@scam -r task2.scm task2.6 > task2.6.results
	#echo "Results:"
	#cat task2.6.results
	#echo "Expected:"
	#cat task2.6.expected
	@diff -s -q task2.6.results task2.6.expected

	#echo "Task2.7:"
	@scam -r task2.scm task2.7 > task2.7.results
	#echo "Results:"
	#cat task2.7.results
	#echo "Expected:"
	#cat task2.7.expected
	@diff -s -q task2.7.results task2.7.expected

	#echo "Task2.8:"
	@scam -r task2.scm task2.8 > task2.8.results
	#echo "Results:"
	#cat task2.8.results
	#echo "Expected:"
	#cat task2.8.expected
	@diff -s -q task2.8.results task2.8.expected

	#echo "Task2.9:"
	@scam -r task2.scm task2.9 > task2.9.results
	#echo "Results:"
	#cat task2.9.results
	#echo "Expected:"
	#cat task2.9.expected
	@diff -s -q task2.9.results task2.9.expected

task3:
	#echo "Task3.0:"
	@scam -r task3.scm task3.0 > task3.0.results
	#echo "Results:"
	#cat task3.0.results
	#echo "Expected:"
	#cat task3.0.expected
	@diff -s -q task3.0.results task3.0.expected

	#echo "Task3.1:"
	@scam -r task3.scm task3.1 > task3.1.results
	#echo "Results:"
	#cat task3.1.results
	#echo "Expected:"
	#cat task3.1.expected
	@diff -s -q task3.1.results task3.1.expected

	#echo "Task3.2:"
	@scam -r task3.scm task3.2 > task3.2.results
	#echo "Results:"
	#cat task3.2.results
	#echo "Expected:"
	#cat task3.2.expected
	@diff -s -q task3.2.results task3.2.expected

	#echo "Task3.3:"
	@scam -r task3.scm task3.3 > task3.3.results
	#echo "Results:"
	#cat task3.3.results
	#echo "Expected:"
	#cat task3.3.expected
	@diff -s -q task3.3.results task3.3.expected

	#echo "Task3.4:"
	@scam -r task3.scm task3.4 > task3.4.results
	#echo "Results:"
	#cat task3.4.results
	#echo "Expected:"
	#cat task3.4.expected
	@diff -s -q task3.4.results task3.4.expected

	#echo "Task3.5:"
	@scam -r task3.scm task3.5 > task3.5.results
	#echo "Results:"
	#cat task3.5.results
	#echo "Expected:"
	#cat task3.5.expected
	@diff -s -q task3.5.results task3.5.expected

	#echo "Task3.6:"
	@scam -r task3.scm task3.6 > task3.6.results
	#echo "Results:"
	#cat task3.6.results
	#echo "Expected:"
	#cat task3.6.expected
	@diff -s -q task3.6.results task3.6.expected

	#echo "Task3.7:"
	@scam -r task3.scm task3.7 > task3.7.results
	#echo "Results:"
	#cat task3.7.results
	#echo "Expected:"
	#cat task3.7.expected
	@diff -s -q task3.7.results task3.7.expected

	#echo "Task3.8:"
	@scam -r task3.scm task3.8 > task3.8.results
	#echo "Results:"
	#cat task3.8.results
	#echo "Expected:"
	#cat task3.8.expected
	@diff -s -q task3.8.results task3.8.expected

	#echo "Task3.9:"
	@scam -r task3.scm task3.9 > task3.9.results
	#echo "Results:"
	#cat task3.9.results
	#echo "Expected:"
	#cat task3.9.expected
	@diff -s -q task3.9.results task3.9.expected

task4:
	#echo "Task4.0:"
	@scam -r task4.scm task4.0 > task4.0.results
	#echo "Results:"
	#cat task4.0.results
	#echo "Expected:"
	#cat task4.0.expected
	@diff -s -q task4.0.results task4.0.expected

	#echo "Task4.1:"
	@scam -r task4.scm task4.1 > task4.1.results
	#echo "Results:"
	#cat task4.1.results
	#echo "Expected:"
	#cat task4.1.expected
	@diff -s -q task4.1.results task4.1.expected

	#echo "Task4.2:"
	@scam -r task4.scm task4.2 > task4.2.results
	#echo "Results:"
	#cat task4.2.results
	#echo "Expected:"
	#cat task4.2.expected
	@diff -s -q task4.2.results task4.2.expected

	#echo "Task4.3:"
	@scam -r task4.scm task4.3 > task4.3.results
	#echo "Results:"
	#cat task4.3.results
	#echo "Expected:"
	#cat task4.3.expected
	@diff -s -q task4.3.results task4.3.expected

	#echo "Task4.4:"
	@scam -r task4.scm task4.4 > task4.4.results
	#echo "Results:"
	#cat task4.4.results
	#echo "Expected:"
	#cat task4.4.expected
	@diff -s -q task4.4.results task4.4.expected

	#echo "Task4.5:"
	@scam -r task4.scm task4.5 > task4.5.results
	#echo "Results:"
	#cat task4.5.results
	#echo "Expected:"
	#cat task4.5.expected
	@diff -s -q task4.5.results task4.5.expected

task5:
	#echo "Task5.0:"
	@scam -r task5.scm task5.0 > task5.0.results
	#echo "Results:"
	#cat task5.0.results
	#echo "Expected:"
	#cat task5.0.expected
	@diff -s -q task5.0.results task5.0.expected

	#echo "Task5.1:"
	@scam -r task5.scm task5.1 > task5.1.results
	#echo "Results:"
	#cat task5.1.results
	#echo "Expected:"
	#cat task5.1.expected
	@diff -s -q task5.1.results task5.1.expected

	#echo "Task5.2:"
	@scam -r task5.scm task5.2 > task5.2.results
	#echo "Results:"
	#cat task5.2.results
	#echo "Expected:"
	#cat task5.2.expected
	@diff -s -q task5.2.results task5.2.expected

	#echo "Task5.3:"
	@scam -r task5.scm task5.3 > task5.3.results
	#echo "Results:"
	#cat task5.3.results
	#echo "Expected:"
	#cat task5.3.expected
	@diff -s -q task5.3.results task5.3.expected

	#echo "Task5.4:"
	@scam -r task5.scm task5.4 > task5.4.results
	#echo "Results:"
	#cat task5.4.results
	#echo "Expected:"
	#cat task5.4.expected
	@diff -s -q task5.4.results task5.4.expected

	#echo "Task5.5:"
	@scam -r task5.scm task5.5 > task5.5.results
	#echo "Results:"
	#cat task5.5.results
	#echo "Expected:"
	#cat task5.5.expected
	@diff -s -q task5.5.results task5.5.expected

	#echo "Task5.6:"
	@scam -r task5.scm task5.6 > task5.6.results
	#echo "Results:"
	#cat task5.6.results
	#echo "Expected:"
	#cat task5.6.expected
	@diff -s -q task5.6.results task5.6.expected

	#echo "Task5.7:"
	@scam -r task5.scm task5.7 > task5.7.results
	#echo "Results:"
	#cat task5.7.results
	#echo "Expected:"
	#cat task5.7.expected
	@diff -s -q task5.7.results task5.7.expected

	#echo "Task5.8:"
	@scam -r task5.scm task5.8 > task5.8.results
	#echo "Results:"
	#cat task5.8.results
	#echo "Expected:"
	#cat task5.8.expected
	@diff -s -q task5.8.results task5.8.expected

	#echo "Task5.9:"
	@scam -r task5.scm task5.9 > task5.9.results
	#echo "Results:"
	#cat task5.9.results
	#echo "Expected:"
	#cat task5.9.expected
	@diff -s -q task5.9.results task5.9.expected

task6:
	#echo "Task6.0:"
	@scam -r task6.scm task6.0 > task6.0.results
	#echo "Results:"
	#cat task6.0.results
	#echo "Expected:"
	#cat task6.0.expected
	@diff -s -q task6.0.results task6.0.expected

	#echo "Task6.1:"
	@scam -r task6.scm task6.1 > task6.1.results
	#echo "Results:"
	#cat task6.1.results
	#echo "Expected:"
	#cat task6.1.expected
	@diff -s -q task6.1.results task6.1.expected

	#echo "Task6.2:"
	@scam -r task6.scm task6.2 > task6.2.results
	#echo "Results:"
	#cat task6.2.results
	#echo "Expected:"
	#cat task6.2.expected
	@diff -s -q task6.2.results task6.2.expected

	#echo "Task6.3:"
	@scam -r task6.scm task6.3 > task6.3.results
	#echo "Results:"
	#cat task6.3.results
	#echo "Expected:"
	#cat task6.3.expected
	@diff -s -q task6.3.results task6.3.expected

	#echo "Task6.4:"
	@scam -r task6.scm task6.4 > task6.4.results
	#echo "Results:"
	#cat task6.4.results
	#echo "Expected:"
	#cat task6.4.expected
	@diff -s -q task6.4.results task6.4.expected

	#echo "Task6.6:"
	@scam -r task6.scm task6.5 > task6.5.results
	#echo "Results:"
	#cat task6.5.results
	#echo "Expected:"
	#cat task6.5.expected
	@diff -s -q task6.5.results task6.5.expected

	#echo "Task6.6:"
	@scam -r task6.scm task6.6 > task6.6.results
	#echo "Results:"
	#cat task6.6.results
	#echo "Expected:"
	#cat task6.6.expected
	@diff -s -q task6.6.results task6.6.expected

	#echo "Task6.7:"
	@scam -r task6.scm task6.7 > task6.7.results
	#echo "Results:"
	#cat task6.7.results
	#echo "Expected:"
	#cat task6.7.expected
	@diff -s -q task6.7.results task6.7.expected

	#echo "Task6.8:"
	@scam -r task6.scm task6.8 > task6.8.results
	#echo "Results:"
	#cat task6.8.results
	#echo "Expected:"
	#cat task6.8.expected
	@diff -s -q task6.8.results task6.8.expected

	#echo "Task6.9:"
	@scam -r task6.scm task6.9 > task6.9.results
	#echo "Results:"
	#cat task6.9.results
	#echo "Expected:"
	#cat task6.9.expected
	@diff -s -q task6.9.results task6.9.expected

task7:
	#echo "Task7.0:"
	@scam -r task7.scm task7.0 > task7.0.results
	#echo "Results:"
	#cat task7.0.results
	#echo "Expected:"
	#cat task7.0.expected
	@diff -s -q task7.0.results task7.0.expected

	#echo "Task7.1:"
	@scam -r task7.scm task7.1 > task7.1.results
	#echo "Results:"
	#cat task7.1.results
	#echo "Expected:"
	#cat task7.1.expected
	@diff -s -q task7.1.results task7.1.expected

	#echo "Task7.2:"
	@scam -r task7.scm task7.2 > task7.2.results
	#echo "Results:"
	#cat task7.2.results
	#echo "Expected:"
	#cat task7.2.expected
	@diff -s -q task7.2.results task7.2.expected

	#echo "Task7.3:"
	@scam -r task7.scm task7.3 > task7.3.results
	#echo "Results:"
	#cat task7.3.results
	#echo "Expected:"
	#cat task7.3.expected
	@diff -s -q task7.3.results task7.3.expected

	#echo "Task7.4:"
	@scam -r task7.scm task7.4 > task7.4.results
	#echo "Results:"
	#cat task7.4.results
	#echo "Expected:"
	#cat task7.4.expected
	@diff -s -q task7.4.results task7.4.expected

	#echo "Task7.5:"
	@scam -r task7.scm task7.5 > task7.5.results
	#echo "Results:"
	#cat task7.5.results
	#echo "Expected:"
	#cat task7.5.expected
	@diff -s -q task7.5.results task7.5.expected

	#echo "Task7.6:"
	@scam -r task7.scm task7.6 > task7.6.results
	#echo "Results:"
	#cat task7.6.results
	#echo "Expected:"
	#cat task7.6.expected
	@diff -s -q task7.6.results task7.6.expected

	#echo "Task7.7:"
	@scam -r task7.scm task7.7 > task7.7.results
	#echo "Results:"
	#cat task7.7.results
	#echo "Expected:"
	#cat task7.7.expected
	@diff -s -q task7.7.results task7.7.expected

	#echo "Task7.8:"
	@scam -r task7.scm task7.8 > task7.8.results
	#echo "Results:"
	#cat task7.8.results
	#echo "Expected:"
	#cat task7.8.expected
	@diff -s -q task7.8.results task7.8.expected

	#echo "Task7.9:"
	@scam -r task7.scm task7.9 > task7.9.results
	#echo "Results:"
	#cat task7.9.results
	#echo "Expected:"
	#cat task7.9.expected
	@diff -s -q task7.9.results task7.9.expected

task8:
	#echo "Task8.0:"
	@scam -r task8.scm task8.0 > task8.0.results
	#echo "Results:"
	#cat task8.0.results
	#echo "Expected:"
	#cat task8.0.expected
	@diff -s -q task8.0.results task8.0.expected

	#echo "Task8.1:"
	@scam -r task8.scm task8.1 > task8.1.results
	#echo "Results:"
	#cat task8.1.results
	#echo "Expected:"
	#cat task8.1.expected
	@diff -s -q task8.1.results task8.1.expected

	#echo "Task8.2:"
	@scam -r task8.scm task8.2 > task8.2.results
	#echo "Results:"
	#cat task8.2.results
	#echo "Expected:"
	#cat task8.2.expected
	@diff -s -q task8.2.results task8.2.expected

	#echo "Task8.3:"
	@scam -r task8.scm task8.3 > task8.3.results
	#echo "Results:"
	#cat task8.3.results
	#echo "Expected:"
	#cat task8.3.expected
	@diff -s -q task8.3.results task8.3.expected

	#echo "Task8.4:"
	@scam -r task8.scm task8.4 > task8.4.results
	#echo "Results:"
	#cat task8.4.results
	#echo "Expected:"
	#cat task8.4.expected
	@diff -s -q task8.4.results task8.4.expected

	#echo "Task8.5:"
	@scam -r task8.scm task8.5 > task8.5.results
	#echo "Results:"
	#cat task8.5.results
	#echo "Expected:"
	#cat task8.5.expected
	@diff -s -q task8.5.results task8.5.expected

	#echo "Task8.6:"
	@scam -r task8.scm task8.6 > task8.6.results
	#echo "Results:"
	#cat task8.6.results
	#echo "Expected:"
	#cat task8.6.expected
	@diff -s -q task8.6.results task8.6.expected

	#echo "Task8.7:"
	@scam -r task8.scm task8.7 > task8.7.results
	#echo "Results:"
	#cat task8.7.results
	#echo "Expected:"
	#cat task8.7.expected
	@diff -s -q task8.7.results task8.7.expected

	#echo "Task8.8:"
	@scam -r task8.scm task8.8 > task8.8.results
	#echo "Results:"
	#cat task8.8.results
	#echo "Expected:"
	#cat task8.8.expected
	@diff -s -q task8.8.results task8.8.expected

	#echo "Task8.9:"
	@scam -r task8.scm task8.9 > task8.9.results
	#echo "Results:"
	#cat task8.8.results
	#echo "Expected:"
	#cat task8.8.expected
	@diff -s -q task8.9.results task8.9.expected

clean:
	@rm *results