(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (setNilDisplay 'nil)
    (readArgs)
)

(define (readArgs)
    (define env this)
    (define (iter expr)
        (if (not (eof?))
            (begin (eval expr env) 
                (iter (readExpr))
            )
        )
    )
    (iter (readExpr))
)

(define (scoping variable object)
    'free
)